name: build-test-deploy
on:
  push:
    branches:
    - gh-pages
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3.9.1
        with:
          node-version-file: .nvmrc
      # ---------------------------------------
      - name: Setup Cache for Node Dependencies
        uses: actions/cache@v4
        with:
          path: |
            .cache
            node_modules
          key: ${{ runner.os }}-gatsby-build-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-gatsby-build-
      - name: Setup Cache for Binaries
        uses: actions/cache@v4
        with:
          path: |
            public
            storybook-static
          key: ${{ runner.os }}-gatsby-build-${{ hashFiles('public/**', 'storybook-static/**') }}
      - run: npm install --global yarn
      - run: yarn install
      - run: |
          node -e "console.log('Node heap_size_limit: %s', v8.getHeapStatistics().heap_size_limit/(1024*1024))"
          export NODE_OPTIONS=--max-old-space-size=5048
          yarn run build
          yarn run build:storybook

  test:
    needs: build
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      # -------------------------------------
      - uses: actions/setup-node@v3.9.1
        with:
          node-version-file: .nvmrc
      # -------------------------------------
      - uses: actions/cache@v4
        with:
          path: |
            .cache
            node_modules
          key: ${{ runner.os }}-gatsby-build-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-gatsby-build-
      # -------------------------------------
      - run: yarn run test

  deploy:
    needs: test
    runs-on: ubuntu-22.04
    permissions:
      contents: write
      pages: write
      id-token: write
    environment:
      name: production
      url: ${{ steps.myDeployment.outputs.page_url }}
    steps:
      - name: Checking out Repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      # -------------------------------------
      - name: Setting up Node
        uses: actions/setup-node@v3.9.1
        with:
          node-version-file: .nvmrc
          cache: yarn
      # -------------------------------------
      - name: Caching Node-Packages
        uses: actions/cache@v4
        with:
          path: |
            .cache
            node_modules
          key: ${{ runner.os }}-gatsby-build-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-gatsby-build-
      - name: Restore Binaries cache
        uses: actions/cache@v4
        with:
          path: |
            public
            storybook-static
          key: ${{ runner.os }}-gatsby-build-${{ hashFiles('public/**', 'storybook-static/**') }}
      # -------------------------------------
      - name: Configuring Github-Pages
        uses: actions/configure-pages@v4
        with:
          static_site_generator: gatsby
      # -------------------------------------
      - name: Building Code for Publishing
        run: |
          mv storybook-static public/storybook
      # -------------------------------------
      - name: Uploading Public Folder
        uses: actions/upload-pages-artifact@v3
        with:
          path: './public'
      # -------------------------------------
      - name: Deployment to Pages
        id: myDeployment
        uses: actions/deploy-pages@v4